In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 150)

In [2]:
import pandas as pd

df = pd.read_excel("../data/raw/indian-job-market-dataset-2025.xlsx")

print("Dataset Loaded Successfully!")
print(df.shape)

Dataset Loaded Successfully!
(97929, 17)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97929 entries, 0 to 97928
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              97929 non-null  str
 1   jobId              97929 non-null  int64
 2   currency           97929 non-null  str
 3   jobUploaded        97929 non-null  str
 4   companyName        97925 non-null  str
 5   tagsAndSkills      97358 non-null  str
 6   experience         95824 non-null  str
 7   salary             97929 non-null  str
 8   location           97929 non-null  str
 9   companyId          97929 non-null  int64
 10  ReviewsCount       62677 non-null  float64
 11  AggregateRating    62677 non-null  float64
 12  jobDescription     97929 non-null  str
 13  minimumSalary      97358 non-null  float64
 14  maximumSalary      97358 non-null  float64
 15  minimumExperience  97358 non-null  float64
 16  maximumExperience  97358 non-null  float64
dtypes: float64(6), int64(2), str(9)
memory usage: 12.7 MB

In [5]:
df.head()

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Power,Hiring,Recruitment,SR,Communication skills",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire Safety,Fire Engineering,Fire Prevention,Safety Management,Fire Management,Hazard Analysis",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as Fire Hydrant system,Fire extinguishers,Fire Alarm smoke detector system,Sprinkler system keep in good...",300000.0,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth marketing,Paid Marketing,Acquisition,Performance,Usage,Marketing",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- School). <br><br>Experience <br><br> 12+ years exp in Digital Marketing with a focus on performance mar...,0.0,0.0,12.0,18.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Communication,Medical,Medical billing,Billing,Fluent,English",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,NaN,NaN,Job Title-Medical Billing Executive\nLocation-Mohali\nSalary-20-22k ctc\n\nBenefits:\nCab facility\nIncentives\nOne time meal\n\nQualification-12 ...,70000.0,200000.0,0.0,3.0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephrology,Group Product Management,Brand Marketing,Neurology,Brand Management",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please write all the major jobs that the employee is required to carry out )<br><br>Making visual aid and cy...,800000.0,1800000.0,5.0,10.0

In [6]:
df.tail()

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
97924,"CNC Machine Maintenance Engineer @ Manali, Chennai",270925008790,INR,6 Days Ago,GSH Group,"CNC Maintenance,CNC Machines,Electrical Maintenance,Maintenance,Machine,Machine maintenance,CNC,Electricals",2-5 Yrs,"50,000-2 Lacs PA","Chennai, Thiruvallur",938550,284.0,4.2,Experience: Minimum 2+ Years in CNC Machine Electrical Maintenance. Qualification: ITI / Diploma / BE <br><br>Required Skills: . Strong knowledge...,50000.0,200000.0,2.0,5.0
97925,IT Cum Digital Marketing Executive,270925008668,INR,6 Days Ago,Luxus Green Mobility Pvt. Ltd.,"Google AdWords,Digital Marketing,Social Media Marketing,SEO,Search Engine Optimization,Marketing,Media,Social media",1-2 Yrs,Not disclosed,Bilaspur,123904985,13.0,2.6,<p> </p><p><strong>Position Overview :-</strong></p><p>We are seeking a dynamic and versatile IT Executive / Digital Marketing Executive who can m...,0.0,0.0,1.0,2.0
97926,Senior Research Associate,270925008467,INR,6 Days Ago,Cadila Pharmaceuticals,"Analytical Method Validation,Analytical Method Development,Analytical,Adl,Method development,Senior,Analytics,Research",4-9 Yrs,Not disclosed,Ahmedabad,14957,2134.0,3.4,Documentation as per GLP requirement,0.0,0.0,4.0,9.0
97927,Customer Care Associate,270925008099,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Strong Communication Skills,Customer care,English,Fluent,Communication skills",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Zirakpur",123804403,NaN,NaN,Job title-Customer Care Associate\nJob location-Chandigarh\nSalary-22-23in hand\n\nQualification-Graduated/Postgraduated\nRotational shifts\nFluen...,70000.0,200000.0,0.0,3.0
97928,Client Relationship Executive,270925008094,INR,6 Days Ago,Logon Global Solutions,"Client Support,English,Client Coordination,Malayalam,Client Servicing,Client Relation,Client Relationship,Relationship",0-3 Yrs,1.92-3.36 Lacs PA,Kochi(Kakkanad),125008981,4.0,4.2,<p> <strong>Role:</strong> Primary advisor for study abroad candidates.</p><ul><li><strong>Focus:</strong> Deliver high-touch client service.</li>...,192000.0,336000.0,0.0,3.0

In [7]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.shape

Rows: 97929
Columns: 17

(97929, 17)

In [8]:
df.columns.tolist()

['title',
 'jobId',
 'currency',
 'jobUploaded',
 'companyName',
 'tagsAndSkills',
 'experience',
 'salary',
 'location',
 'companyId',
 'ReviewsCount',
 'AggregateRating',
 'jobDescription',
 'minimumSalary',
 'maximumSalary',
 'minimumExperience',
 'maximumExperience']

In [9]:
missing = df.isnull().sum().sort_values(ascending=False)

missing[missing > 0]

AggregateRating      35252
ReviewsCount         35252
experience            2105
minimumSalary          571
tagsAndSkills          571
maximumExperience      571
maximumSalary          571
minimumExperience      571
companyName              4
dtype: int64

In [10]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 247

In [11]:
df.dtypes

title                    str
jobId                  int64
currency                 str
jobUploaded              str
companyName              str
tagsAndSkills            str
experience               str
salary                   str
location                 str
companyId              int64
ReviewsCount         float64
AggregateRating      float64
jobDescription           str
minimumSalary        float64
maximumSalary        float64
minimumExperience    float64
maximumExperience    float64
dtype: object

In [12]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
title,97929,55104,Application Developer,2039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
jobId,97929.0,NaN,NaN,NaN,206985423051.857239,99878601476.771545,10125001764.0,180825009352.0,250825003714.0,280825021346.0,311224008927.0
currency,97929,2,INR,97800,NaN,NaN,NaN,NaN,NaN,NaN,NaN
jobUploaded,97929,30,4 Days Ago,13973,NaN,NaN,NaN,NaN,NaN,NaN,NaN
companyName,97925,18668,Accenture,8204,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tagsAndSkills,97358,84307,"Retail,Lead generation,Forex,Investment products,Sales,Customer satisfaction,Business Development Associate,Financial services",116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
experience,95824,287,5-10 Yrs,6448,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary,97929,1339,Not disclosed,64076,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location,97929,10066,Bengaluru,16823,NaN,NaN,NaN,NaN,NaN,NaN,NaN
companyId,97929.0,NaN,NaN,NaN,27846420.597821,49791844.09429,3.0,233939.0,2892790.0,6398332.0,125142239.0
ReviewsCount,62677.0,NaN,NaN,NaN,14662.590264,24744.514682,2.0,65.0,962.0,12826.0,104449.0
AggregateRating,62677.0,NaN,NaN,NaN,3.679048,0.484096,1.0,3.5,3.7,3.9,5.0
jobDescription,97929,80679,Disclaimer: This job description has been sourced from a public domain and may have been modified by Naukri.com to improve clarity for our users,382,NaN,NaN,NaN,NaN,NaN,NaN,NaN
minimumSalary,97358.0,NaN,NaN,NaN,198309.204914,564076.482815,0.0,0.0,0.0,200000.0,70000000.0
maximumSalary,97358.0,NaN,NaN,NaN,318609.580846,841733.620322,0.0,0.0,0.0,375000.0,95000000.0
minimumExperience,97358.0,NaN,NaN,NaN,3.957744,3.581196,0.0,1.0,3.0,5.0,30.0
maximumExperience,97358.0,NaN,NaN,NaN,7.732647,4.500161,0.0,5.0,7.0,10.0,35.0

In [13]:
df.to_csv("../data/processed/master_jobs.csv", index=False)

print("Master dataset saved successfully!")

Master dataset saved successfully!