In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("../data/processed/master_jobs.csv")

print("Dataset Loaded Successfully!")
print(df.shape)

Dataset Loaded Successfully!
(97929, 17)

In [3]:
df.head()

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- Sch...,0.0,0.0,12.0,18.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,NaN,NaN,Job Title-Medical Billing Executive\nLocation-...,70000.0,200000.0,0.0,3.0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please w...,800000.0,1800000.0,5.0,10.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97929 entries, 0 to 97928
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              97929 non-null  str
 1   jobId              97929 non-null  int64
 2   currency           97929 non-null  str
 3   jobUploaded        97929 non-null  str
 4   companyName        97925 non-null  str
 5   tagsAndSkills      97358 non-null  str
 6   experience         95824 non-null  str
 7   salary             97929 non-null  str
 8   location           97929 non-null  str
 9   companyId          97929 non-null  int64
 10  ReviewsCount       62677 non-null  float64
 11  AggregateRating    62677 non-null  float64
 12  jobDescription     97929 non-null  str
 13  minimumSalary      97358 non-null  float64
 14  maximumSalary      97358 non-null  float64
 15  minimumExperience  97358 non-null  float64
 16  maximumExperience  97358 non-null  float64
dtypes: float64(6), int64(2), str(9)
memory usage: 12.7 MB

In [5]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

missing = missing[missing["Missing Values"]>0]

missing.sort_values("Missing Values", ascending=False)

                   Missing Values  Percentage
AggregateRating             35252   35.997508
ReviewsCount                35252   35.997508
experience                   2105    2.149516
minimumSalary                 571    0.583075
tagsAndSkills                 571    0.583075
minimumExperience             571    0.583075
maximumSalary                 571    0.583075
maximumExperience             571    0.583075
companyName                     4    0.004085

In [6]:
print("Duplicates Before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates After:", df.duplicated().sum())

Duplicates Before: 247
Duplicates After: 0

In [7]:
threshold = len(df) * 0.60

df = df.dropna(axis=1, thresh=threshold)

print(df.shape)

(97682, 17)

In [8]:
df.columns.tolist()

['title',
 'jobId',
 'currency',
 'jobUploaded',
 'companyName',
 'tagsAndSkills',
 'experience',
 'salary',
 'location',
 'companyId',
 'ReviewsCount',
 'AggregateRating',
 'jobDescription',
 'minimumSalary',
 'maximumSalary',
 'minimumExperience',
 'maximumExperience']

In [9]:
numeric_cols = df.select_dtypes(include=np.number).columns

df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

In [10]:
categorical_cols = df.select_dtypes(include="object").columns

df[categorical_cols] = df[categorical_cols].fillna("Unknown")

C:\Users\sande\AppData\Local\Temp\ipykernel_11572\1570884024.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

In [11]:
df.isnull().sum().sort_values(ascending=False).head(20)

title                0
jobId                0
currency             0
jobUploaded          0
companyName          0
tagsAndSkills        0
experience           0
salary               0
location             0
companyId            0
ReviewsCount         0
AggregateRating      0
jobDescription       0
minimumSalary        0
maximumSalary        0
minimumExperience    0
maximumExperience    0
dtype: int64

In [12]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("-", "_")
)

df.columns.tolist()

['title',
 'jobid',
 'currency',
 'jobuploaded',
 'companyname',
 'tagsandskills',
 'experience',
 'salary',
 'location',
 'companyid',
 'reviewscount',
 'aggregaterating',
 'jobdescription',
 'minimumsalary',
 'maximumsalary',
 'minimumexperience',
 'maximumexperience']

In [13]:
[col for col in df.columns if "salary" in col]

['salary', 'minimumsalary', 'maximumsalary']

In [14]:
text_columns = [
    "title",
    "company_name",
    "location"
]

for col in text_columns:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip()

In [18]:
df["experience"].value_counts(dropna=False)

experience
5-10 Yrs     6433
3-8 Yrs      5746
1-3 Yrs      3904
2-5 Yrs      3767
1-6 Yrs      3620
             ...
8-25 Yrs        1
21-30 Yrs       1
13 Yrs          1
1-17 Yrs        1
19-29 Yrs       1
Name: count, Length: 288, dtype: int64

In [16]:
for col in df.columns:
    print(col)

title
jobid
currency
jobuploaded
companyname
tagsandskills
experience
salary
location
companyid
reviewscount
aggregaterating
jobdescription
minimumsalary
maximumsalary
minimumexperience
maximumexperience

In [17]:
[col for col in df.columns if "experience" in col.lower()]

['experience', 'minimumexperience', 'maximumexperience']

In [19]:
df["minimumexperience"].describe()

count    97682.000000
mean         3.952704
std          3.571799
min          0.000000
25%          1.000000
50%          3.000000
75%          5.000000
max         30.000000
Name: minimumexperience, dtype: float64

In [20]:
df["maximumexperience"].describe()

count    97682.00000
mean         7.72863
std          4.48734
min          0.00000
25%          5.00000
50%          7.00000
75%         10.00000
max         35.00000
Name: maximumexperience, dtype: float64

In [21]:
# Create average experience

df["avg_experience"] = (
    df["minimumexperience"] +
    df["maximumexperience"]
) / 2

df[["minimumexperience",
    "maximumexperience",
    "avg_experience"]].head()

   minimumexperience  maximumexperience  avg_experience
0                2.0                4.0             3.0
1                6.0               11.0             8.5
2               12.0               18.0            15.0
3                0.0                3.0             1.5
4                5.0               10.0             7.5

In [22]:
df.to_csv("../data/processed/cleaned_jobs.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!